#############################################################################
# Makefile for building: libFrameworkQt.a
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Jul 11 21:44:11 2012
# Project:  QtFramework.pro
# Template: lib
# Command: /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-xcode -o FrameworkQt.xcodeproj/project.pbxproj QtFramework.pro
#############################################################################

QMAKE    = /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake
FrameworkQt.xcodeproj/project.pbxproj: QtFramework.pro  /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-xcode/qmake.conf /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/staticlib.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/static.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtMultimedia.framework/QtMultimedia.prl \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl \
		/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtNetwork.framework/QtNetwork.prl
	$(QMAKE) -spec /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-xcode -o FrameworkQt.xcodeproj/project.pbxproj QtFramework.pro
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/unix.conf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/mac.conf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base.conf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/gcc-base-macx.conf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-base.conf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/common/g++-macx.conf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/qconfig.pri:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/modules/qt_webkit_version.pri:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_functions.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt_config.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/exclusive_builds.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_pre.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_pre.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/dwarf2.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/debug.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/default_post.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/default_post.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86_64.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/objective_c.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/x86.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/staticlib.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/static.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/warn_on.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/qt.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/opengl.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/unix/thread.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/moc.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/rez.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/mac/sdk.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/resources.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/uic.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/yacc.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/lex.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/features/include_source_dir.prf:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtMultimedia.framework/QtMultimedia.prl:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtGui.framework/QtGui.prl:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/QtCore.prl:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/QtOpenGL.prl:
/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtNetwork.framework/QtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-xcode -o FrameworkQt.xcodeproj/project.pbxproj QtFramework.pro

