#############################################################################
# Makefile for building: libFrameworkQt.a
# Generated by qmake (2.01a) (Qt 4.8.1) on: Wed Jul 11 21:44:11 2012
# Project:  QtFramework.pro
# Template: lib
# Command: /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/bin/qmake -spec /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-xcode -o FrameworkQt.xcodeproj/project.pbxproj QtFramework.pro
#############################################################################

MOC       = /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/bin/moc
UIC       = /Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/bin/uic
LEX       = flex
LEXFLAGS  = 
YACC      = yacc
YACCFLAGS = -d
DEFINES       = -DDDARWIN_NO_CARBON -DFT2_BUILD_LIBRARY -DQ_OS_MAC -DDAVA_DEBUG -DQT_MULTIMEDIA_LIB -DQT_OPENGL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
INCPATH       = -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/mkspecs/macx-xcode -I. -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtCore.framework/Versions/4/Headers -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtCore -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtNetwork.framework/Versions/4/Headers -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtNetwork -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtOpenGL.framework/Versions/4/Headers -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtOpenGL -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib/QtMultimedia.framework/Versions/4/Headers -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/include/QtMultimedia -I/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/include -I../../Sources/Internal -I../../Sources/External -I../../Sources/External/Freetype -I../../Libs/oggvorbis/include -I../../Libs/include -I../../Libs/libs -I../../Libs/freetype/include -I../../Libs/oggvorbis/include -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -I/usr/local/include -I/System/Library/Frameworks/CarbonCore.framework/Headers -F/Users/klesch/QtSDK/Desktop/Qt/4.8.1/gcc/lib
DEL_FILE  = rm -f
MOVE      = mv -f

IMAGES = 
PARSERS =
preprocess: $(PARSERS) compilers
clean preprocess_clean: parser_clean compiler_clean

parser_clean:
check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compilers: ./FileSystemObjective.o ./LoggerMacOS.o ./BaseNetworkConnection.o\
	 ./BTNetworkConnection.o ./NetworkConnectionIPhone.o ./TCPServer.o\
	 ./WFNetworkConnection.o ./ThreadMacOS.o ./CursorMacOS.o\
	 ./HTTPDownloader.o ./UtilsMacOS.o
compiler_objective_c_make_all: FileSystemObjective.o LoggerMacOS.o BaseNetworkConnection.o BTNetworkConnection.o NetworkConnectionIPhone.o TCPServer.o WFNetworkConnection.o ThreadMacOS.o CursorMacOS.o HTTPDownloader.o UtilsMacOS.o
compiler_objective_c_clean:
	-$(DEL_FILE) FileSystemObjective.o LoggerMacOS.o BaseNetworkConnection.o BTNetworkConnection.o NetworkConnectionIPhone.o TCPServer.o WFNetworkConnection.o ThreadMacOS.o CursorMacOS.o HTTPDownloader.o UtilsMacOS.o
FileSystemObjective.o: ../../Sources/Internal/FileSystem/FileSystemObjective.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/FileSystem/FileSystemObjective.mm -o FileSystemObjective.o

LoggerMacOS.o: ../../Sources/Internal/FileSystem/LoggerMacOS.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/FileSystem/LoggerMacOS.mm -o LoggerMacOS.o

BaseNetworkConnection.o: ../../Sources/Internal/Network/BaseNetworkConnection.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Network/BaseNetworkConnection.mm -o BaseNetworkConnection.o

BTNetworkConnection.o: ../../Sources/Internal/Network/BTNetworkConnection.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Network/BTNetworkConnection.mm -o BTNetworkConnection.o

NetworkConnectionIPhone.o: ../../Sources/Internal/Network/NetworkConnectionIPhone.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Network/NetworkConnectionIPhone.mm -o NetworkConnectionIPhone.o

TCPServer.o: ../../Sources/Internal/Network/TCPServer.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Network/TCPServer.mm -o TCPServer.o

WFNetworkConnection.o: ../../Sources/Internal/Network/WFNetworkConnection.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Network/WFNetworkConnection.mm -o WFNetworkConnection.o

ThreadMacOS.o: ../../Sources/Internal/Platform/ThreadMacOS.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Platform/ThreadMacOS.mm -o ThreadMacOS.o

CursorMacOS.o: ../../Sources/Internal/Render/CursorMacOS.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Render/CursorMacOS.mm -o CursorMacOS.o

HTTPDownloader.o: ../../Sources/Internal/Utils/HTTPDownloader.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Utils/HTTPDownloader.mm -o HTTPDownloader.o

UtilsMacOS.o: ../../Sources/Internal/Utils/UtilsMacOS.mm
	gcc -c $(QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS) $(DEFINES) $(INCPATH) ../../Sources/Internal/Utils/UtilsMacOS.mm -o UtilsMacOS.o

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_objective_c_clean 

