#pragma once

#include "Command/CommandIDs.h"

enum CommandID : DAVA::CommandID_t
{
    CMDID_ADD_COMPONENT = DAVA::CMDID_USER,
    CMDID_ADD_REMOVE_STYLE_PROPERTY,
    CMDID_ADD_REMOVE_STYLE_SELECTOR,
    CMDID_ATTACH_COMPONENT_PROTOTYPE_SECTION,
    CMDID_CHANGE_PROPERTY_VALUE,
    CMDID_CHANGE_STYLE_PROPERTY,
    CMDID_INSERT_CONTROL,
    CMDID_INSERT_IMPORTED_PACKAGE,
    CMDID_INSERT_REMOVE_STYLE,
    CMDID_REMOVE_COMPONENT,
    CMDID_REMOVE_CONTROL,
    CMDID_REMOVE_IMPORTED_PACKAGE
};
