if ( DAVA_TOOLS_FOUND )
    return ()
endif ()
set ( DAVA_TOOLS_FOUND 1 )

get_filename_component( CURRENT_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH CACHE )
add_subdirectory ( "${CURRENT_DIR}/../../Tools" ${CMAKE_CURRENT_BINARY_DIR}/DavaTools )
set( DAVA_TOOLS_LIBRARY    DavaTools )


set( DAVA_ADDITIONAL_DYNAMIC_LIBRARIES_MAC ${DAVA_THIRD_PARTY_ROOT_PATH}/IMagickHelpLib/libIMagickHelper.dylib  )
set( DAVA_ADDITIONAL_DYNAMIC_LIBRARIES_WIN ${DAVA_TOOLS_BIN_DIR}/IMagickHelper.dll )

append_property( DAVA_ADDITIONAL_DYNAMIC_LIBRARIES_MAC ${DAVA_ADDITIONAL_DYNAMIC_LIBRARIES_MAC} ) 
append_property( DAVA_ADDITIONAL_DYNAMIC_LIBRARIES_WIN ${DAVA_ADDITIONAL_DYNAMIC_LIBRARIES_WIN} ) 