macro(define_ngt_pathes ngt_root)
    get_filename_component( NGT_ROOT ${ngt_root} ABSOLUTE )
    set                   ( NGT_SRC_ROOT "${NGT_ROOT}/src/core/")
    set                   ( NGT_CORE_PATH "${NGT_SRC_ROOT}lib/")
    set                   ( NGT_PLUGINS_PATH "${NGT_SRC_ROOT}plugins/")
endmacro()

macro(get_subdirs_list result curdir)
    file(GLOB children RELATIVE ${curdir} ${curdir}/*)
        set(dirlist "")
        foreach(child ${children})
            if(IS_DIRECTORY ${curdir}/${child})
                list(APPEND dirlist ${child})
            endif()
        endforeach()
    set(${result} ${dirlist})
endmacro()

macro ( define_ngt_lib FOLDER_PATH LIB_NAME)
    set(${LIB_NAME}_PATH ${FOLDER_PATH})
    set(${LIB_NAME}_FOUND 1)
endmacro ()

macro (append_ngt_lib LIB_NAME)
    add_subdirectory(${${LIB_NAME}_PATH} "ngt/${LIB_NAME}")
    SET_PROPERTY( TARGET ${LIB_NAME} PROPERTY FOLDER "NGT Core")
endmacro()

macro (append_ngt_plugin LIB_NAME)
    add_subdirectory(${${LIB_NAME}_PATH} "ngt/${LIB_NAME}")
    SET_PROPERTY( TARGET ${LIB_NAME} PROPERTY FOLDER "NGT Plugins")
endmacro()
