#ifndef __RESOURCEEDITORQT_TEXTURECONVERTMODE_H__
#define __RESOURCEEDITORQT_TEXTURECONVERTMODE_H__

enum eTextureConvertMode
{
    CONVERT_FORCE = 0,
    CONVERT_MODIFIED,
    CONVERT_NOT_EXISTENT,
    
    CONVERT_MODES_COUNT
};

#endif