#ifndef __SCENE_NODE_IDS_H__
#define __SCENE_NODE_IDS_H__

enum eCreateNodeIds
{
    ECNID_LANDSCAPE = 0, 
    ECNID_LIGHT, 
    ECNID_SERVICENODE, 
    ECNID_BOX, 
    ECNID_SPHERE, 
    ECNID_CAMERA, 
	ECNID_IMPOSTER,
	ECNID_PARTICLE_EMITTER,
	ECNID_USERNODE,

//	ECNID_LODNODE,
    
    
    ECNID_COUNT
};


#endif // __SCENE_NODE_IDS_H__