#pragma once

#include <Command/CommandIDs.h>

enum eQECommmandIDs : DAVA::CommandID
{
    ADD_COMPONENT_COMMAND = DAVA::USER_COMMAND,
    ADD_STYLE_PROPERTY_COMMAND,
    ADD_STYLE_SELECTOR_COMMAND,
    REMOVE_STYLE_PROPERTY_COMMAND,
    REMOVE_STYLE_SELECTOR_COMMAND,
    ATTACH_COMPONENT_PROTOTYPE_SECTION_COMMAND,
    CHANGE_PROPERTY_VALUE_COMMAND,
    RESIZE_COMMAND,
    CHANGE_PIVOT_COMMAND,
    CHANGE_STYLE_PROPERTY_COMMAND,
    CHANGE_MULTIPLE_PROPERTIES_VALUE_COMMAND,
    INSERT_CONTROL_COMMAND,
    INSERT_IMPORTED_PACKAGE_COMMAND,
    INSERT_STYLE_COMMAND,
    REMOVE_STYLE_COMMAND,
    REMOVE_COMPONENT_COMMAND,
    REMOVE_CONTROL_COMMAND,
    REMOVE_IMPORTED_PACKAGE_COMMAND,
};
