import binascii
import os.path
import filecmp
from PIL import Image, ImageChops

#from PIL import Image

# Function for comparing files, generated by UIEditor
def compare_txt(expected, actual):  
    if not os.path.exists(actual):
        return "File is not created: " + actual
            
    if not filecmp.cmp(expected,actual):
        return "File %s is not equal to expected" % actual

def compare_tex(expected, actual):
    if not os.path.exists(actual):
        return "File is not created: " + actual
    
    text1 = open(expected, "rb").read() # Read expecting reult from file
    text2 = open(actual, "rb").read() # Read actual result from generated file
    
    text1_hex = binascii.hexlify(text1)
    text2_hex = binascii.hexlify(text2)
    
    if text1_hex != text2_hex:
        return "Tex files are not equals: %s\n%s\n%s" %(actual, text1_hex, text2_hex)

   
def compare_img(expected, actual):
    if not os.path.exists(actual):
        return "File is not created: " + actual
    
    im1 = Image.open(expected)
    im2 = Image.open(actual)
    
    if not (ImageChops.difference(im1, im2).getbbox() is None):
    #if im1.tostring() != im2.tostring():
        return "File %s is not equal to expected" % actual