#if defined(__DAVAENGINE_WINDOWS__)
#include "Input/Private/KeyboardDeviceImplWinCodes.h"

namespace DAVA
{
namespace Private
{
const eInputElements nativeScancodeToDavaScancode[] =
{
  eInputElements::NONE, // 0x00
  eInputElements::KB_ESCAPE_SCANCODE, // 0x01
  eInputElements::KB_1_SCANCODE, // 0x02
  eInputElements::KB_2_SCANCODE, // 0x03
  eInputElements::KB_3_SCANCODE, // 0x04
  eInputElements::KB_4_SCANCODE, // 0x05
  eInputElements::KB_5_SCANCODE, // 0x06
  eInputElements::KB_6_SCANCODE, // 0x07
  eInputElements::KB_7_SCANCODE, // 0x08
  eInputElements::KB_8_SCANCODE, // 0x09
  eInputElements::KB_9_SCANCODE, // 0x0A
  eInputElements::KB_0_SCANCODE, // 0x0B
  eInputElements::KB_MINUS_SCANCODE, // 0x0C
  eInputElements::KB_EQUALS_SCANCODE, // 0x0D
  eInputElements::KB_BACKSPACE_SCANCODE, // 0x0E
  eInputElements::KB_TAB_SCANCODE, // 0x0F
  eInputElements::KB_Q_SCANCODE, // 0x10
  eInputElements::KB_W_SCANCODE, // 0x11
  eInputElements::KB_E_SCANCODE, // 0x12
  eInputElements::KB_R_SCANCODE, // 0x13
  eInputElements::KB_T_SCANCODE, // 0x14
  eInputElements::KB_Y_SCANCODE, // 0x15
  eInputElements::KB_U_SCANCODE, // 0x16
  eInputElements::KB_I_SCANCODE, // 0x17
  eInputElements::KB_O_SCANCODE, // 0x18
  eInputElements::KB_P_SCANCODE, // 0x19
  eInputElements::KB_LBRACKET_SCANCODE, // 0x1A
  eInputElements::KB_RBRACKET_SCANCODE, // 0x1B
  eInputElements::KB_ENTER_SCANCODE, // 0x1C
  eInputElements::KB_LCTRL_SCANCODE, // 0x1D
  eInputElements::KB_A_SCANCODE, // 0x1E
  eInputElements::KB_S_SCANCODE, // 0x1F
  eInputElements::KB_D_SCANCODE, // 0x20
  eInputElements::KB_F_SCANCODE, // 0x21
  eInputElements::KB_G_SCANCODE, // 0x22
  eInputElements::KB_H_SCANCODE, // 0x23
  eInputElements::KB_J_SCANCODE, // 0x24
  eInputElements::KB_K_SCANCODE, // 0x25
  eInputElements::KB_L_SCANCODE, // 0x26
  eInputElements::KB_SEMICOLON_SCANCODE, // 0x27
  eInputElements::KB_APOSTROPHE_SCANCODE, // 0x28
  eInputElements::KB_GRAVE_SCANCODE, // 0x29
  eInputElements::KB_LSHIFT_SCANCODE, // 0x2A
  eInputElements::KB_BACKSLASH_SCANCODE, // 0x2B
  eInputElements::KB_Z_SCANCODE, // 0x2C
  eInputElements::KB_X_SCANCODE, // 0x2D
  eInputElements::KB_C_SCANCODE, // 0x2E
  eInputElements::KB_V_SCANCODE, // 0x2F
  eInputElements::KB_B_SCANCODE, // 0x30
  eInputElements::KB_N_SCANCODE, // 0x31
  eInputElements::KB_M_SCANCODE, // 0x32
  eInputElements::KB_COMMA_SCANCODE, // 0x33
  eInputElements::KB_PERIOD_SCANCODE, // 0x34
  eInputElements::KB_SLASH_SCANCODE, // 0x35
  eInputElements::KB_RSHIFT_SCANCODE, // 0x36
  eInputElements::KB_MULTIPLY_SCANCODE, // 0x37
  eInputElements::KB_LALT_SCANCODE, // 0x38
  eInputElements::KB_SPACE_SCANCODE, // 0x39
  eInputElements::KB_CAPSLOCK_SCANCODE, // 0x3A
  eInputElements::KB_F1_SCANCODE, // 0x3B
  eInputElements::KB_F2_SCANCODE, // 0x3C
  eInputElements::KB_F3_SCANCODE, // 0x3D
  eInputElements::KB_F4_SCANCODE, // 0x3E
  eInputElements::KB_F5_SCANCODE, // 0x3F
  eInputElements::KB_F6_SCANCODE, // 0x40
  eInputElements::KB_F7_SCANCODE, // 0x41
  eInputElements::KB_F8_SCANCODE, // 0x42
  eInputElements::KB_F9_SCANCODE, // 0x43
  eInputElements::KB_F10_SCANCODE, // 0x44
  eInputElements::KB_PAUSE_SCANCODE, // 0x45
  eInputElements::KB_SCROLLLOCK_SCANCODE, // 0x46
  eInputElements::KB_NUMPAD_7_SCANCODE, // 0x47
  eInputElements::KB_NUMPAD_8_SCANCODE, // 0x48
  eInputElements::KB_NUMPAD_9_SCANCODE, // 0x49
  eInputElements::KB_NUMPAD_MINUS_SCANCODE, // 0x4A
  eInputElements::KB_NUMPAD_4_SCANCODE, // 0x4B
  eInputElements::KB_NUMPAD_5_SCANCODE, // 0x4C
  eInputElements::KB_NUMPAD_6_SCANCODE, // 0x4D
  eInputElements::KB_NUMPAD_PLUS_SCANCODE, // 0x4E
  eInputElements::KB_NUMPAD_1_SCANCODE, // 0x4F
  eInputElements::KB_NUMPAD_2_SCANCODE, // 0x50
  eInputElements::KB_NUMPAD_3_SCANCODE, // 0x51
  eInputElements::KB_NUMPAD_0_SCANCODE, // 0x52
  eInputElements::KB_NUMPAD_DELETE_SCANCODE, // 0x53
  eInputElements::NONE, // 0x54
  eInputElements::NONE, // 0x55
  eInputElements::KB_NONUSBACKSLASH_SCANCODE, // 0x56
  eInputElements::KB_F11_SCANCODE, // 0x57
  eInputElements::KB_F12_SCANCODE, // 0x58
};

const eInputElements nativeScancodeExtToDavaScancode[] =
{
  eInputElements::NONE, // 0x00
  eInputElements::NONE, // 0x01
  eInputElements::NONE, // 0x02
  eInputElements::NONE, // 0x03
  eInputElements::NONE, // 0x04
  eInputElements::NONE, // 0x05
  eInputElements::NONE, // 0x06
  eInputElements::NONE, // 0x07
  eInputElements::NONE, // 0x08
  eInputElements::NONE, // 0x09
  eInputElements::NONE, // 0x0A
  eInputElements::NONE, // 0x0B
  eInputElements::NONE, // 0x0C
  eInputElements::NONE, // 0x0D
  eInputElements::NONE, // 0x0E
  eInputElements::NONE, // 0x0F
  eInputElements::NONE, // 0x10
  eInputElements::NONE, // 0x11
  eInputElements::NONE, // 0x12
  eInputElements::NONE, // 0x13
  eInputElements::NONE, // 0x14
  eInputElements::NONE, // 0x15
  eInputElements::NONE, // 0x16
  eInputElements::NONE, // 0x17
  eInputElements::NONE, // 0x18
  eInputElements::NONE, // 0x19
  eInputElements::NONE, // 0x1A
  eInputElements::NONE, // 0x1B
  eInputElements::KB_NUMPAD_ENTER_SCANCODE, // 0x1C
  eInputElements::KB_RCTRL_SCANCODE, // 0x1D
  eInputElements::NONE, // 0x1E
  eInputElements::NONE, // 0x1F
  eInputElements::NONE, // 0x20
  eInputElements::NONE, // 0x21
  eInputElements::NONE, // 0x22
  eInputElements::NONE, // 0x23
  eInputElements::NONE, // 0x24
  eInputElements::NONE, // 0x25
  eInputElements::NONE, // 0x26
  eInputElements::NONE, // 0x27
  eInputElements::NONE, // 0x28
  eInputElements::NONE, // 0x29
  eInputElements::NONE, // 0x2A
  eInputElements::NONE, // 0x2B
  eInputElements::NONE, // 0x2C
  eInputElements::NONE, // 0x2D
  eInputElements::NONE, // 0x2E
  eInputElements::NONE, // 0x2F
  eInputElements::NONE, // 0x30
  eInputElements::NONE, // 0x31
  eInputElements::NONE, // 0x32
  eInputElements::NONE, // 0x33
  eInputElements::NONE, // 0x34
  eInputElements::KB_DIVIDE_SCANCODE, // 0x35
  eInputElements::NONE, // 0x36
  eInputElements::KB_PRINTSCREEN_SCANCODE, // 0x37
  eInputElements::KB_RALT_SCANCODE, // 0x38
  eInputElements::NONE, // 0x39
  eInputElements::NONE, // 0x3A
  eInputElements::NONE, // 0x3B
  eInputElements::NONE, // 0x3C
  eInputElements::NONE, // 0x3D
  eInputElements::NONE, // 0x3E
  eInputElements::NONE, // 0x3F
  eInputElements::NONE, // 0x40
  eInputElements::NONE, // 0x41
  eInputElements::NONE, // 0x42
  eInputElements::NONE, // 0x43
  eInputElements::NONE, // 0x44
  eInputElements::KB_NUMLOCK_SCANCODE, // 0x45
  eInputElements::NONE, // 0x46
  eInputElements::KB_HOME_SCANCODE, // 0x47
  eInputElements::KB_UP_SCANCODE, // 0x48
  eInputElements::KB_PAGEUP_SCANCODE, // 0x49
  eInputElements::NONE, // 0x4A
  eInputElements::KB_LEFT_SCANCODE, // 0x4B
  eInputElements::NONE, // 0x4C
  eInputElements::KB_RIGHT_SCANCODE, // 0x4D
  eInputElements::NONE, // 0x4E
  eInputElements::KB_END_SCANCODE, // 0x4F
  eInputElements::KB_DOWN_SCANCODE, // 0x50
  eInputElements::KB_PAGEDOWN_SCANCODE, // 0x51
  eInputElements::KB_INSERT_SCANCODE, // 0x52
  eInputElements::KB_DELETE_SCANCODE, // 0x53
  eInputElements::NONE, // 0x54
  eInputElements::NONE, // 0x55
  eInputElements::NONE, // 0x56
  eInputElements::NONE, // 0x57
  eInputElements::NONE, // 0x58
  eInputElements::NONE, // 0x59
  eInputElements::NONE, // 0x5A
  eInputElements::KB_LWIN_SCANCODE, // 0x5B
  eInputElements::KB_RWIN_SCANCODE, // 0x5C
  eInputElements::KB_MENU_SCANCODE, // 0x5D
};
}
}
#endif
