#include "QtTools/EditorPreferences/Actions/AbstractAction.h"
#include "QtTools/EditorPreferences/Actions/BoolAction.h"
#include "QtTools/EditorPreferences/Actions/IntAction.h"
#include "QtTools/EditorPreferences/Actions/DoubleAction.h"
#include "QtTools/EditorPreferences/Actions/StringAction.h"
#include "QtTools/EditorPreferences/Actions/ColorAction.h"
