#!/usr/bin/env bash
set -e

clients_num=64
bot_kind=random
log_stats=false

OPTIND=1
while getopts ":c:b:s" opt; do
  case $opt in
    c)
      clients_num=$OPTARG
      ;;
    b)
      bot_kind=$OPTARG
      ;;
    s)
      log_stats=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

port=${1}
dir=${2:-dev}
secret=${3:-secret.tfvars}

ssh_opts="-o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
server=18.184.36.67

hosts=(`aws/aws-ips ${dir} ${secret}`)

hosts_num=${#hosts[@]}
clients_num_per_host=$((clients_num / hosts_num))

host_id=1
for host in ${hosts[@]}; do
    if [ ${hosts_num} -gt 1 ] && [ ${host_id} == ${hosts_num} ]; then
		clients_num_per_host=$((clients_num_per_host + clients_num - hosts_num * clients_num_per_host))
	fi

	ssh ${ssh_opts} ec2-user@${host} \
        "LD_LIBRARY_PATH=~/_game/app BOT_APP=~/_game/app/Client bash ~/run_bots.sh ${clients_num_per_host} ${server} ${port} ${host_id} ${bot_kind} ${log_stats} </dev/null 1>clients-out.log 2>clients-err.log &"

    host_id=$((host_id + 1))

done
echo "CLIENTS: ${hosts[@]}"
