VPROG_IN_BEGIN
    VPROG_IN_POSITION
    VPROG_IN_COLOR0
VPROG_IN_END

VPROG_OUT_BEGIN
    VPROG_OUT_POSITION
    VPROG_OUT_COLOR0(color,4)
VPROG_OUT_END

property float4x4 worldViewProjMatrix : dynamic,instance : ;

VPROG_BEGIN

    float3 in_pos      = VP_IN_POSITION;
    float4 in_color    = VP_IN_COLOR0;

    VP_OUT_POSITION = mul( float4(in_pos.x, in_pos.y, in_pos.z, 1.0), worldViewProjMatrix );
    VP_OUT(color) =  in_color;
    
VPROG_END
