#!/bin/sh

exec_clang_format() 
{
	files="${1}"
	python codeformat/git-clang-format.py --binary codeformat/clang-format --style file ${files}
	error_code=$?

	if [ $error_code -ne 0 ]; then
        exit $error_code
    else
		git add ${files}
    fi  
}

files=""

# collect files that should be formated during this commit
for file in `git diff-index --cached --name-only HEAD` ; do

	# collect only existed files
	if [ -f ${file} ]; then

		# collect only file, that are
		# matched specified extensions 
		case "$file" in
			*.c | *.cc |*.cpp | *.h | *.hh |*.hpp | *.mm | *.cxx)
				files="$files $file"
			;;
			*)
			;;
		esac

		# if collected files string length is greater 
		# than 2048 exec clang format
		if [ ${#files} -ge 4096 ]; then
			exec_clang_format "${files}"
			files=""
		fi
	fi
done

# exec clang format for the rest files
exec_clang_format "${files}"
