#include "common.cgh"
#include "blending.cgh"

VPROG_IN_BEGIN
    VPROG_IN_POSITION        
VPROG_IN_END

VPROG_OUT_BEGIN
    VPROG_OUT_POSITION
    VPROG_OUT_TEXCOORD0(screenSpaceCoordinates,4)
VPROG_OUT_END

property float4x4 worldViewProjMatrix : dynamic,a : ;

VPROG_BEGIN
	VP_OUT(screenSpaceCoordinates) = mul(VP_IN_POSITION, worldViewProjMatrix);
	VP_OUT_POSITION = VP_OUT(screenSpaceCoordinates);
VPROG_END