# CMake generated Testfile for 
# Source directory: E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_repo/Tests/CMakeOnly
# Build directory: E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeOnly.LinkInterfaceLoop "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=LinkInterfaceLoop" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
set_tests_properties(CMakeOnly.LinkInterfaceLoop PROPERTIES  TIMEOUT "90")
add_test(CMakeOnly.CheckSymbolExists "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=CheckSymbolExists" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXSymbolExists "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=CheckCXXSymbolExists" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckCXXCompilerFlag "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=CheckCXXCompilerFlag" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckLanguage "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=CheckLanguage" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CheckStructHasMember "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=CheckStructHasMember" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdC "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=CompilerIdC" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.CompilerIdCXX "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=CompilerIdCXX" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.AllFindModules "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=AllFindModules" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.SelectLibraryConfigurations "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=SelectLibraryConfigurations" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.TargetScope "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=TargetScope" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_library "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=find_library" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.find_path "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=find_path" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.ProjectInclude "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=ProjectInclude" "-DCMAKE_ARGS=-DCMAKE_PROJECT_ProjectInclude_INCLUDE=E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_repo/Tests/CMakeOnly/ProjectInclude/include.cmake" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_2 "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonLibs_3 "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=MajorVersionSelection-PythonLibs_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonLibs;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=PYTHONLIBS_VERSION_STRING" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_2 "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_2" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=2;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-PythonInterp_3 "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=MajorVersionSelection-PythonInterp_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=PythonInterp;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=TRUE;-DMAJOR_TEST_VERSION_VAR=PYTHON_VERSION_STRING" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_3 "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=MajorVersionSelection-Qt_3" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=3;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
add_test(CMakeOnly.MajorVersionSelection-Qt_4 "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/bin/cmake" "-DTEST=MajorVersionSelection-Qt_4" "-DTEST_SOURCE=MajorVersionSelection" "-DCMAKE_ARGS=-DMAJOR_TEST_MODULE=Qt;-DMAJOR_TEST_VERSION=4;-DMAJOR_TEST_NO_LANGUAGES=FALSE;-DMAJOR_TEST_VERSION_VAR=QT_VERSION_STRING" "-P" "E:/repo/WindowsStore/dava.framework/Tools/WinStoreCMake/cmake_build/Tests/CMakeOnly/Test.cmake")
