#!/usr/bin/env bash

set -e
set -x

mkdir -p /tmp/dava.framework/Programs/UnitTests/build

export CC=clang
export CXX=clang++
cd /tmp/dava.framework/Programs/UnitTests/build
cmake3 -DDEPLOY=true -DCMAKE_BUILD_TYPE=Release .. && make -j 4
