#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "llvm-gcc -D_DARWIN_C_SOURCE -DOPENSSL_BN_ASM_PART_WORDS -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Wed Feb  5 13:45:02 EET 2014"
#endif
